spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/shop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true print sql by system.out
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug # print sql by logger
    org.hibernate.type: trace # parameter data trace